# *** This Dockefile is generated by KloverCloud *** #
FROM golang:latest as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /app/bin/go .

FROM golang:latest

RUN useradd -ms /bin/bash klovercloud

WORKDIR /home/klovercloud

COPY --from=builder /app/bin .


EXPOSE 4040

USER klovercloud
CMD ["./go"]