package constant

const (
	INVALID_BUCKET        = "INVALID_BUCKET"
	INVALID_INPUT         = "INVALID_INPUT"
	EMPTY_ACCESS_KEY      = "EMPTY_ACCESS_KEY"
	EMPTY_SECRET          = "EMPTY_SECRET"
	INVALID_ENDPOINT      = "INVALID_ENDPOINT"
	UNAUTHORIZED          = "UNAUTHORIZED"
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
	STATUS_SUCCESS        = "SUCCESS"
)
